import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const myFont = localFont({
  src: [
    {
      path: '../fonts/CircularSpotifyText-Light.otf',
      weight: '300',
      style: 'light'
    },
    {
      path: '../fonts/CircularSpotifyText-Black.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/CircularSpotifyText-Medium.otf',
      weight: '500',
      style: 'medium'
    },
    {
      path: '../fonts/CircularSpotifyText-Bold.otf',
      weight: '700',
      style: 'bold'
    }
  ]
})

export default function RootLayout({
  children
}: {
  // eslint-disable-next-line no-undef
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={myFont.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
